---

updates:
  - package-ecosystem: 'maven'
    target-branch: 'main'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'github-actions'
    target-branch: 'main'
    directory: '.github/workflows'
    schedule:
      interval: 'daily'
