---

version: 2

updates:
  - package-ecosystem: maven
    commit-message:
      prefix: 'chore(maven): '
    directory: '/'
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    commit-message:
      prefix: 'chore(github-actions): '
    directory: '/'
    schedule:
      interval: daily
